{% set host = app + '.' + domain %}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ service }}
  labels:
    app: {{ service }}
spec:
  tls:
  - hosts:
    - {{ host }}
    secretName: tls
  rules:
    - host: {{ host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ service }}
            servicePort: 5000
